### ISSUE TITLE
下拉加载, 有时候会崩溃

### ISSUE THREAD

**Issue by 1024042400** [zhangyao0328/RecyclerViewMore#1]
08-16 16:51:22.673 32609-32609/com.recyclerviewmore W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
08-16 16:51:22.678 32609-32609/com.recyclerviewmore E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.recyclerviewmore, PID: 32609
                                                                      java.lang.IllegalStateException: Added View has RecyclerView as parent but view is not a real child. Unfiltered index:0
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:7109)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7073)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:7061)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1428)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                          at android.view.View.layout(View.java:15137)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                          at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:613)
                                                                          at android.view.View.layout(View.java:15137)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                          at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                                                                          at android.view.View.layout(View.java:15137)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                          at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                          at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                          at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1364)
                                                                          at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:846)
                                                                          at android.view.View.layout(View.java:15137)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                          at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1197)
                                                                          at android.view.View.layout(View.java:15137)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
                                                                          at android.view.View.layout(View.java:15137)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
                                                                          at android.view.View.layout(View.java:15137)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
                                                                          at android.view.View.layout(View.java:15137)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
                                                                          at android.view.View.layout(View.java:15137)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
                                                                          at android.view.View.layout(View.java:15137)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:4862)
                                                                          at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2323)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2029)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                          at android.os.Handler.handleCallback(Handler.java:808)
                                                                      	at android

**Comment by 1024042400** [comment]
经测试, 是BaseRecyclerAdapter类的俩个addItems 有问题. 改一改就能正常了
